export { LoginPage } from './login-page'
export { RegisterPage } from './register-page'
export { ForgotPasswordPage } from './forgot-password-page'
export { VerifyCodePage } from './verify-code-page'
export { ResetPasswordPage } from './reset-password-page'
