/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
<<<<<<< HEAD
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UserSettingsRouteImport } from './routes/user/settings'
import { Route as UserCreateClassRouteImport } from './routes/user/create-class'
import { Route as ClassClassIdRouteImport } from './routes/class/$classId'
=======
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ClassesIndexRouteImport } from './routes/classes/index'
import { Route as ClassesCreateClassRouteImport } from './routes/classes/create-class'
>>>>>>> master
import { Route as AuthVerifyCodeRouteImport } from './routes/auth/verify-code'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIndexRoute = ClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesCreateClassRoute = ClassesCreateClassRouteImport.update({
  id: '/classes/create-class',
  path: '/classes/create-class',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassClassIdRoute = ClassClassIdRouteImport.update({
  id: '/class/$classId',
  path: '/class/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyCodeRoute = AuthVerifyCodeRouteImport.update({
  id: '/auth/verify-code',
  path: '/auth/verify-code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-code': typeof AuthVerifyCodeRoute
<<<<<<< HEAD
  '/class/$classId': typeof ClassClassIdRoute
  '/user/create-class': typeof UserCreateClassRoute
  '/user/settings': typeof UserSettingsRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/admin/settings/display': typeof AdminSettingsDisplayRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/user/settings/account': typeof UserSettingsAccountRoute
  '/user/settings/appearance': typeof UserSettingsAppearanceRoute
  '/user/settings/display': typeof UserSettingsDisplayRoute
  '/user/settings/notifications': typeof UserSettingsNotificationsRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/user/dashboard': typeof UserDashboardIndexRoute
  '/user/settings/': typeof UserSettingsIndexRoute
=======
  '/classes/create-class': typeof ClassesCreateClassRoute
  '/classes': typeof ClassesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/profile': typeof ProfileIndexRoute
>>>>>>> master
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-code': typeof AuthVerifyCodeRoute
<<<<<<< HEAD
  '/class/$classId': typeof ClassClassIdRoute
  '/user/create-class': typeof UserCreateClassRoute
  '/admin': typeof AdminIndexRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/admin/settings/display': typeof AdminSettingsDisplayRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/user/settings/account': typeof UserSettingsAccountRoute
  '/user/settings/appearance': typeof UserSettingsAppearanceRoute
  '/user/settings/display': typeof UserSettingsDisplayRoute
  '/user/settings/notifications': typeof UserSettingsNotificationsRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/user/dashboard': typeof UserDashboardIndexRoute
  '/user/settings': typeof UserSettingsIndexRoute
=======
  '/classes/create-class': typeof ClassesCreateClassRoute
  '/classes': typeof ClassesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/profile': typeof ProfileIndexRoute
>>>>>>> master
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-code': typeof AuthVerifyCodeRoute
<<<<<<< HEAD
  '/class/$classId': typeof ClassClassIdRoute
  '/user/create-class': typeof UserCreateClassRoute
  '/user/settings': typeof UserSettingsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/admin/settings/display': typeof AdminSettingsDisplayRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/user/settings/account': typeof UserSettingsAccountRoute
  '/user/settings/appearance': typeof UserSettingsAppearanceRoute
  '/user/settings/display': typeof UserSettingsDisplayRoute
  '/user/settings/notifications': typeof UserSettingsNotificationsRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/user/dashboard/': typeof UserDashboardIndexRoute
  '/user/settings/': typeof UserSettingsIndexRoute
=======
  '/classes/create-class': typeof ClassesCreateClassRoute
  '/classes/': typeof ClassesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/profile/': typeof ProfileIndexRoute
>>>>>>> master
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-code'
<<<<<<< HEAD
    | '/class/$classId'
    | '/user/create-class'
    | '/user/settings'
    | '/admin'
    | '/admin/settings/account'
    | '/admin/settings/appearance'
    | '/admin/settings/display'
    | '/admin/settings/notifications'
    | '/user/settings/account'
    | '/user/settings/appearance'
    | '/user/settings/display'
    | '/user/settings/notifications'
    | '/admin/dashboard'
    | '/admin/settings/'
    | '/user/dashboard'
    | '/user/settings/'
=======
    | '/classes/create-class'
    | '/classes'
    | '/dashboard'
    | '/profile'
>>>>>>> master
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-code'
<<<<<<< HEAD
    | '/class/$classId'
    | '/user/create-class'
    | '/admin'
    | '/admin/settings/account'
    | '/admin/settings/appearance'
    | '/admin/settings/display'
    | '/admin/settings/notifications'
    | '/user/settings/account'
    | '/user/settings/appearance'
    | '/user/settings/display'
    | '/user/settings/notifications'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/user/dashboard'
    | '/user/settings'
=======
    | '/classes/create-class'
    | '/classes'
    | '/dashboard'
    | '/profile'
>>>>>>> master
  id:
    | '__root__'
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-code'
<<<<<<< HEAD
    | '/class/$classId'
    | '/user/create-class'
    | '/user/settings'
    | '/admin/'
    | '/admin/settings/account'
    | '/admin/settings/appearance'
    | '/admin/settings/display'
    | '/admin/settings/notifications'
    | '/user/settings/account'
    | '/user/settings/appearance'
    | '/user/settings/display'
    | '/user/settings/notifications'
    | '/admin/dashboard/'
    | '/admin/settings/'
    | '/user/dashboard/'
    | '/user/settings/'
=======
    | '/classes/create-class'
    | '/classes/'
    | '/dashboard/'
    | '/profile/'
>>>>>>> master
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyCodeRoute: typeof AuthVerifyCodeRoute
<<<<<<< HEAD
  ClassClassIdRoute: typeof ClassClassIdRoute
  UserCreateClassRoute: typeof UserCreateClassRoute
  UserSettingsRoute: typeof UserSettingsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  UserDashboardIndexRoute: typeof UserDashboardIndexRoute
=======
  ClassesCreateClassRoute: typeof ClassesCreateClassRoute
  ClassesIndexRoute: typeof ClassesIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
>>>>>>> master
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/': {
      id: '/classes/'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/create-class': {
      id: '/classes/create-class'
      path: '/classes/create-class'
      fullPath: '/classes/create-class'
      preLoaderRoute: typeof ClassesCreateClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/$classId': {
      id: '/class/$classId'
      path: '/class/$classId'
      fullPath: '/class/$classId'
      preLoaderRoute: typeof ClassClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-code': {
      id: '/auth/verify-code'
      path: '/auth/verify-code'
      fullPath: '/auth/verify-code'
      preLoaderRoute: typeof AuthVerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyCodeRoute: AuthVerifyCodeRoute,
<<<<<<< HEAD
  ClassClassIdRoute: ClassClassIdRoute,
  UserCreateClassRoute: UserCreateClassRoute,
  UserSettingsRoute: UserSettingsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  UserDashboardIndexRoute: UserDashboardIndexRoute,
=======
  ClassesCreateClassRoute: ClassesCreateClassRoute,
  ClassesIndexRoute: ClassesIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
>>>>>>> master
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
